#include "headernames.h"

std::vector<std::string> ndsHeaderNamesArr = {
    "Game Title",
    "Game Code",
    "Maker Code",
    "Unit Code",
    "Device Code",
    "Card Size",
    "Card Info",
    "Flags",
    "ARM9 Rom Address",
    "ARM9 Entry Address",
    "ARM9 Ram Address",
    "ARM9 Size",
    "ARM7 Rom Address",
    "ARM7 Entry Address",
    "ARM7 Ram Address",
    "ARM7 Size",
    "Filename Table Address",
    "Filename Table Size",
    "FAT Address",
    "FAT Size",
    "ARM9 Overlay Address",
    "ARM9 Overlay Size",
    "ARM7 Overlay Address",
    "ARM7 Overlay Size",
    "Port 40001A4h NC",
    "Port 40001a4h KC",
    "Icon/Title Address",
    "Secure Area CRC16",
    "Secure Area Timeout",
    "ARM9 AL Ram Address",
    "ARM7 AL Ram Address",
    "Secure Area Disable",
    "Used Rom Size",
    "Header Size",
    "Nintendo Logo",
    "Nintendo Logo CRC",
    "Header CRC",
    "Debug Rom Address",
    "Debug Size",
    "Debug Ram Address",
    "FAT Files Address"
};
